In [2]:
# date_range()函数的使用
import pandas as pd
pd.date_range('2021-1-1',periods=10,freq='W')

DatetimeIndex(['2021-01-03', '2021-01-10', '2021-01-17', '2021-01-24',
               '2021-01-31', '2021-02-07', '2021-02-14', '2021-02-21',
               '2021-02-28', '2021-03-07'],
              dtype='datetime64[ns]', freq='W-SUN')

In [7]:
# 将一分钟时间序列转换成3分钟
index=pd.date_range('2021-1-1',periods=9,freq='T')

s=pd.Series(data=range(9),index=index)

# 产生3分钟的序列
#s.resample(rule='3T',how='sum')
s.resample(rule='3T').sum()

2021-01-01 00:00:00     3
2021-01-01 00:03:00    12
2021-01-01 00:06:00    21
Freq: 3T, dtype: int64

In [1]:
import pandas as pd
df=pd.read_excel('msb课程销售记录.xlsx')
df=df.set_index('订单付款时间')
#df.head()
df.resample('W').sum()

,会员名,实际支付金额,课程名称,学员姓名,联系手机
订单付款时间,,,,,
2020-05-10,xrd1h82,14480,大数据全栈工程师,杨某某,1**********
2020-05-17,xf142eh4jnqh8641mk55a,26340,从零基础开始学Python大数据多线程与高并发第二版大数据全栈工程师,杜某某黄某某周某某,1**********1**********1**********
2020-05-24,5ax69ek,8880,从零基础开始学Python大数据,张某某,1**********
2020-05-31,j7dnasa9gxur51,11860,多线程与高并发第二版从零基础开始学Python大数据,刘某某高某某,1**********1**********
2020-06-07,8q0vey12cvkognal57mqn,30940,Java零基础后端工程师多线程与高并发第二版Java高级互联网架构师,郭先生李先生刘先生,1***********1***********1***********
2020-06-14,ksajlku9p04wyh9t70iwkkzynh5civl58bm,55900,Java零基础后端工程师Java零基础后端工程师Java高级互联网架构师Java零基础后端工...,车先生陈先生张先生范先生t先生,1***********1***********1***********1*********...
2020-06-21,1qyoqb55b0bycj,30960,Java高级互联网架构师Java高级互联网架构师,许先生颜先生,1***********1***********
2020-06-28,0,0,0,0,0
2020-07-05,0,0,0,0,0
2020-07-12,h73ahuxhql0x4h,24960,Java零基础后端工程师Java零基础后端工程师,吴某某张某某,1**********1**********
2020-07-19,oycih87,15480,Java高级互联网架构师,陈某某,1**********
2020-07-26,hxbfh6k,14480,大数据全栈工程师,侯某某,1**********
2020-08-02,0,0,0,0,0
2020-08-09,097qj9vbal5jir,26960,大数据全栈工程师Java零基础后端工程师,邵先生邹先生,1**********1**********
2020-08-16,1oxq73yiz2ombh,18460,多线程与高并发第二版Java高级互联网架构师,廖先生周先生,1**********1**********
2020-08-23,e8i59tyw6l2m8g,26960,大数据全栈工程师Java零基础后端工程师,王先生马先生,1**********1**********
2020-08-30,0,0,0,0,0
2020-09-06,m4oj8l0qsv8q69,28960,大数据全栈工程师大数据全栈工程师,虞先生黄先生,1**********1**********
2020-09-13,6pgpixn8n4tnsc,26960,Java零基础后端工程师大数据全栈工程师,于先生朱先生,1**********1**********
2020-09-20,b1kdmy7ujm1bea7pm2ieipbrln4xd8069179sxp8op,70700,大数据全栈工程师多线程与高并发第二版金三银四Java互联网面试突击班大数据全栈工程师大数据全...,宋先生王先生李先生张先生梁先生何先生,1**********1**********1**********1**********1*...
2020-09-27,do78oaq4bru31p,12780,多线程与高并发第二版金三银四Java互联网面试突击班,卢先生郑先生,1**********1**********
2020-10-04,w9knlw7pgbjq6y,29960,大数据全栈工程师Java高级互联网架构师,海先生高先生,1**********1**********
2020-10-11,1n8hvfnqp3nl0x02a6qgs,31940,大数据全栈工程师多线程与高并发第二版大数据全栈工程师,廖先生李先生陈先生,1**********1**********1**********
2020-10-18,t7rax4wkswnqg5nela0g7obsct92tstsxlh,57900,Java零基础后端工程师大数据全栈工程师Java零基础后端工程师多线程与高并发第二版Java...,陈先生王先生李先生张先生周先生,1**********1**********1**********1**********1*...
2020-10-25,1twq7st,2980,多线程与高并发第二版,李先生,1**********

In [5]:
import pandas as pd
df=pd.read_excel('msb课程销售记录.xlsx')
df=df.set_index('订单付款时间')
#df.head()
df.resample('W',closed='left').sum()
# 打印第一列和第三列
df[['实际支付金额']]

                     实际支付金额
订单付款时间
2020-06-21 22:36:00   15480
2020-06-21 18:35:00   15480
2020-06-06 10:38:00   15480
2020-06-10 08:22:00   15480
2020-07-18 05:30:00   15480
2020-08-15 12:25:00   15480
2020-09-28 11:56:00   15480
2020-10-18 17:53:00   15480
2020-09-15 07:54:00    9800
2020-09-24 01:10:00    9800
2020-05-16 09:41:00   14480
2020-05-09 15:31:00   14480
2020-07-23 16:47:00   14480
2020-08-19 09:31:00   14480
2020-08-09 11:27:00   14480
2020-09-28 01:16:00   14480
2020-09-18 08:43:00   14480
2020-09-16 19:16:00   14480
2020-09-15 12:39:00   14480
2020-09-14 09:01:00   14480
2020-09-11 15:02:00   14480
2020-09-06 21:13:00   14480
2020-09-06 19:36:00   14480
2020-10-16 11:27:00   14480
2020-10-11 23:59:00   14480
2020-10-10 12:53:00   14480
2020-06-11 01:56:00   12480
2020-06-09 22:42:00   12480
2020-06-03 08:15:00   12480
2020-06-09 14:21:00   12480
2020-07-11 15:48:00   12480
2020-08-09 12:23:00   12480
2020-09-10 22:57:00   12480
2020-10-17 01:45:00   12480
2020-10-12 10:03:00   12480
2020-07-06 13:53:00   12480
2020-08-23 17:32:00   12480
2020-10-25 21:35:00    2980
2020-05-25 15:21:00    2980
2020-05-14 20:22:00    2980
2020-06-13 16:45:00    2980
2020-06-05 10:22:00    2980
2020-08-10 08:18:00    2980
2020-09-23 23:11:00    2980
2020-09-14 19:52:00    2980
2020-10-18 10:11:00    2980
2020-10-11 17:18:00    2980
2020-05-25 16:19:00    8880
2020-05-24 09:53:00    8880
2020-05-14 10:11:00    8880

In [18]:
import pandas as pd
index=pd.date_range('2020-1-1',periods=2)
s=pd.Series(range(1,3),index=index)
print(s)
# 升采样
s.resample('6H').asfreq()

# 使用前值填充
s.resample('6H').ffill()

# 使用后值填充
# s.resample('6H').bfill()

2020-01-01    1
2020-01-02    2
Freq: D, dtype: int64

C:\Users\厉佳星\AppData\Local\Temp\ipykernel_24836\2885074531.py:6: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  s.resample('6H').asfreq()
C:\Users\厉佳星\AppData\Local\Temp\ipykernel_24836\2885074531.py:9: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  s.resample('6H').ffill()

2020-01-01 00:00:00    1
2020-01-01 06:00:00    1
2020-01-01 12:00:00    1
2020-01-01 18:00:00    1
2020-01-02 00:00:00    2
Freq: 6h, dtype: int64

In [19]:
# 统计数据的open,close ,high,low的值
import pandas as pd
index=pd.date_range('2020-2-3',periods=12,freq='T')
s=pd.Series(range(12),index=index)
s

C:\Users\厉佳星\AppData\Local\Temp\ipykernel_24836\3179399405.py:3: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  index=pd.date_range('2020-2-3',periods=12,freq='T')

2020-02-03 00:00:00     0
2020-02-03 00:01:00     1
2020-02-03 00:02:00     2
2020-02-03 00:03:00     3
2020-02-03 00:04:00     4
2020-02-03 00:05:00     5
2020-02-03 00:06:00     6
2020-02-03 00:07:00     7
2020-02-03 00:08:00     8
2020-02-03 00:09:00     9
2020-02-03 00:10:00    10
2020-02-03 00:11:00    11
Freq: min, dtype: int64

In [32]:
# 统计数据的open,close ,high,low的值
import pandas as pd
index=pd.date_range('2020-2-3',periods=12,freq='T')
s=pd.Series(range(12),index=index)
s.resample('5min').ohlc()

                     open  high  low  close
2020-02-03 00:00:00     0     4    0      4
2020-02-03 00:05:00     5     9    5      9
2020-02-03 00:10:00    10    11   10     11

In [20]:
# 创建淘宝的每日销量数据
import pandas as pd
index=pd.date_range('2020-1-1',periods=15,freq='D')

#创建Series对象
s=pd.Series(data=[3,6,7,4,2,1,3,8,9,10,12,15,13,22,14],index=index)

# 使用rolling函数计算三天的均值
s.rolling(3).mean()

2020-01-01          NaN
2020-01-02          NaN
2020-01-03     5.333333
2020-01-04     5.666667
2020-01-05     4.333333
2020-01-06     2.333333
2020-01-07     2.000000
2020-01-08     4.000000
2020-01-09     6.666667
2020-01-10     9.000000
2020-01-11    10.333333
2020-01-12    12.333333
2020-01-13    13.333333
2020-01-14    16.666667
2020-01-15    16.333333
Freq: D, dtype: float64

In [36]:
# 创建淘宝的每日销量数据
import pandas as pd
index=pd.date_range('2020-1-1',periods=15,freq='D')

#创建Series对象
s=pd.Series(data=[3,6,7,4,2,1,3,8,9,10,12,15,13,22,14],index=index)

# 使用rolling函数计算三天的均值
s.rolling(3,min_periods=1).mean()

2020-01-01     3.000000
2020-01-02     4.500000
2020-01-03     5.333333
2020-01-04     5.666667
2020-01-05     4.333333
2020-01-06     2.333333
2020-01-07     2.000000
2020-01-08     4.000000
2020-01-09     6.666667
2020-01-10     9.000000
2020-01-11    10.333333
2020-01-12    12.333333
2020-01-13    13.333333
2020-01-14    16.666667
2020-01-15    16.333333
Freq: D, dtype: float64