In [15]:
# 设置小数位置
import pandas as pd
df=pd.read_excel('格式化数据.xlsx')
print(df)
print(df.round(2)) # 对df的所有元素起作用  round中的参数是一个整数
print('-------------------------------')

#对指定列保留小数位置
print(df.round({'A1':1,'A2':2})) # round中的参数是一个字典

print('-------------------------------')
s1=pd.Series([1,0,2,1,2],index=['A1','A2','A3','A4','A5'])
print(s1)

print('-------------------------------') #round中的参数是一个Series对象
df2=df.round(s1)
print(df2)

print('-------------------------------') 
# 还可以使用自定义函数实现保留小数位置
df3=df.applymap(lambda x :'{:.2f}'.format(x))
print(df3)

         A1        A2        A3        A4        A5
0  0.527350  0.410396  0.131101  0.565818  0.322695
1  0.007817  0.663029  0.480029  0.551382  0.603932
2  0.123241  0.935813  0.052935  0.207342  0.183324
3  0.405295  0.623856  0.254653  0.368602  0.751753
4  0.195120  0.623856  0.477747  0.592885  0.751753
     A1    A2    A3    A4    A5
0  0.53  0.41  0.13  0.57  0.32
1  0.01  0.66  0.48  0.55  0.60
2  0.12  0.94  0.05  0.21  0.18
3  0.41  0.62  0.25  0.37  0.75
4  0.20  0.62  0.48  0.59  0.75
-------------------------------
    A1    A2        A3        A4        A5
0  0.5  0.41  0.131101  0.565818  0.322695
1  0.0  0.66  0.480029  0.551382  0.603932
2  0.1  0.94  0.052935  0.207342  0.183324
3  0.4  0.62  0.254653  0.368602  0.751753
4  0.2  0.62  0.477747  0.592885  0.751753
-------------------------------
A1    1
A2    0
A3    2
A4    1
A5    2
dtype: int64
-------------------------------
    A1   A2    A3   A4    A5
0  0.5  0.0  0.13  0.6  0.32
1  0.0  1.0  0.48  0.6  0.60
2  0.1  1.0  0.05  0.2  0.18
3  0.4  1.0  0.25  0.4  0.75
4  0.2  1.0  0.48  0.6  0.75
-------------------------------
     A1    A2    A3    A4    A5
0  0.53  0.41  0.13  0.57  0.32
1  0.01  0.66  0.48  0.55  0.60
2  0.12  0.94  0.05  0.21  0.18
3  0.41  0.62  0.25  0.37  0.75
4  0.20  0.62  0.48  0.59  0.75
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
A1    5 non-null object
A2    5 non-null object
A3    5 non-null object
A4    5 non-null object
A5    5 non-null object
dtypes: object(5)
memory usage: 328.0+ bytes
None

In [16]:
#设置百分比
import pandas as pd
df=pd.read_excel('格式化数据.xlsx')
print(df)

print('-----------------------------')
df['百分比']=df['A1'].apply(lambda x:format(x,'.0%')) # 对A1列进行设置百分比
print(df)

print('-----------------------------')
df['百分比']=df['A1'].apply(lambda x:format(x,'.2%')) # 
print(df)


print('-----------------------------')
# map()函数
df['百分比']=df['A1'].map(lambda x:format(x,'.2%')) # 
print(df)

         A1        A2        A3        A4        A5
0  0.527350  0.410396  0.131101  0.565818  0.322695
1  0.007817  0.663029  0.480029  0.551382  0.603932
2  0.123241  0.935813  0.052935  0.207342  0.183324
3  0.405295  0.623856  0.254653  0.368602  0.751753
4  0.195120  0.623856  0.477747  0.592885  0.751753
-----------------------------
         A1        A2        A3        A4        A5  百分比
0  0.527350  0.410396  0.131101  0.565818  0.322695  53%
1  0.007817  0.663029  0.480029  0.551382  0.603932   1%
2  0.123241  0.935813  0.052935  0.207342  0.183324  12%
3  0.405295  0.623856  0.254653  0.368602  0.751753  41%
4  0.195120  0.623856  0.477747  0.592885  0.751753  20%
-----------------------------
         A1        A2        A3        A4        A5     百分比
0  0.527350  0.410396  0.131101  0.565818  0.322695  52.73%
1  0.007817  0.663029  0.480029  0.551382  0.603932   0.78%
2  0.123241  0.935813  0.052935  0.207342  0.183324  12.32%
3  0.405295  0.623856  0.254653  0.368602  0.751753  40.53%
4  0.195120  0.623856  0.477747  0.592885  0.751753  19.51%
-----------------------------
         A1        A2        A3        A4        A5     百分比
0  0.527350  0.410396  0.131101  0.565818  0.322695  52.73%
1  0.007817  0.663029  0.480029  0.551382  0.603932   0.78%
2  0.123241  0.935813  0.052935  0.207342  0.183324  12.32%
3  0.405295  0.623856  0.254653  0.368602  0.751753  40.53%
4  0.195120  0.623856  0.477747  0.592885  0.751753  19.51%
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
A1     5 non-null float64
A2     5 non-null float64
A3     5 non-null float64
A4     5 non-null float64
A5     5 non-null float64
百分比    5 non-null object
dtypes: float64(5), object(1)
memory usage: 368.0+ bytes
None

In [21]:
import pandas as pd
pd.set_option('display.unicode.east_asian_width',True)
df=pd.read_excel('msb课程记录.xls')
print(df)
print(df.info())
print('------------------------------')
df['买家实际支付金额']=df['买家实际支付金额'].apply(lambda x:format(int(x),','))
print(df)
print(df.info())

   买家会员名  买家实际支付金额  课程总数量             课程标题   类别  \
0      msb001          30960.00         2.0  Java互联网高级架构师  课程
1      msb002              1.00         1.0    金三银四面试突击班   NaN
2      msb003           9980.00         1.0    GoLang从入门到精通  课程
3      msb004           9980.00         NaN  算法与数据结构进阶班  课程
4      msb005              9.90         1.0       大前端VIP体验营   NaN
5      msb006              0.02         1.0  零基础速成班HTML+CSS  课程
6      msb007           2400.00         1.0              操作系统  课程
7      msb008              1.00         NaN            自定义注解  课程
8      msb009           2980.00         1.0        多线程与高并发  课程
9      msb010           1980.00         1.0              科技英语  课程
10     msb010           1980.00         1.0              科技英语  课程

          订单付款时间
0  2020-10-09 22:54:26
1  2020-10-09 22:52:42
2  2020-01-19 12:53:01
3  2020-06-30 11:46:14
4  2020-03-23 18:25:45
5  2020-03-24 19:25:45
6  2020-03-25 11:00:45
7  2020-03-26 23:11:11
8  2020-03-27 07:25:30
9  2020-03-28 18:09:12
10 2020-03-28 18:09:12
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
买家会员名       11 non-null object
买家实际支付金额    11 non-null float64
课程总数量       9 non-null float64
课程标题        11 non-null object
类别          9 non-null object
订单付款时间      11 non-null datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 656.0+ bytes
None
------------------------------
   买家会员名 买家实际支付金额  课程总数量             课程标题   类别  \
0      msb001           30,960         2.0  Java互联网高级架构师  课程
1      msb002                1         1.0    金三银四面试突击班   NaN
2      msb003            9,980         1.0    GoLang从入门到精通  课程
3      msb004            9,980         NaN  算法与数据结构进阶班  课程
4      msb005                9         1.0       大前端VIP体验营   NaN
5      msb006                0         1.0  零基础速成班HTML+CSS  课程
6      msb007            2,400         1.0              操作系统  课程
7      msb008                1         NaN            自定义注解  课程
8      msb009            2,980         1.0        多线程与高并发  课程
9      msb010            1,980         1.0              科技英语  课程
10     msb010            1,980         1.0              科技英语  课程

          订单付款时间
0  2020-10-09 22:54:26
1  2020-10-09 22:52:42
2  2020-01-19 12:53:01
3  2020-06-30 11:46:14
4  2020-03-23 18:25:45
5  2020-03-24 19:25:45
6  2020-03-25 11:00:45
7  2020-03-26 23:11:11
8  2020-03-27 07:25:30
9  2020-03-28 18:09:12
10 2020-03-28 18:09:12
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
买家会员名       11 non-null object
买家实际支付金额    11 non-null object
课程总数量       9 non-null float64
课程标题        11 non-null object
类别          9 non-null object
订单付款时间      11 non-null datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 656.0+ bytes
None

In [33]:
# apply(),map(),applymap()区别
#apply()可以在Series，对Series的每一个元素都执行一次函数，也可以在DataFrame中起作用，对DataFrame中的某一行或某一列的每个元素扫许一次函数
import pandas as pd
s=pd.Series(data=[10,20,30,40],index=['a','b','c','d'])
print(s)
print('-------------------------------------')
s=s.apply(lambda x:x+10)
print(s)

print('----------------------------------')
df=pd.DataFrame(data=[[10,20,30,40],[11,22,33,44]],index=['a','b'],columns=['A','B','C','D'])
print(df)

print('----------------------------------')
df2=df.apply(lambda x:x.sum(),axis=0) # 0表示行，1表示列，默认是行运算
print(df2)

print('----------------------------------')
df2=df.apply(lambda x:x.sum(),axis=1) # 0表示行，1表示列，默认是行运算
print(df2)

# map只能应用在Series的每个元素上
df=pd.DataFrame(data=[['男'],['女'],['男'],['男']],index=['张三','李四','王五','陈六'],columns=['性别'])
print(df)

def gender(g):
    if g=='男':
        return 0
    else:
        return 1
print('----------------------------------')
# map的参数是一个函数
#print(type(df['性别'])) df['性别']是一个Series对象
df2=df['性别'].map(gender)  # 参数是一个函数
print(df2)
print('----------------------------------')
# map()的参数还可以是一个字典
df3=df['性别'].map({'男':0,'女':1})
print(df3)
              
# applymap()将函数应用到DataFrame中的每一个元素中  ，与apply()的区别，apply()只能应用到某列或某行
df=pd.DataFrame(data=[[10,20,30,40],[11,22,33,44]],index=['a','b'],columns=['A','B','C','D'])
print(df)

df=df.applymap(lambda x:x+10)
print(df)

a    10
b    20
c    30
d    40
dtype: int64
-------------------------------------
a    20
b    30
c    40
d    50
dtype: int64
----------------------------------
    A   B   C   D
a  10  20  30  40
b  11  22  33  44
----------------------------------
A    21
B    42
C    63
D    84
dtype: int64
----------------------------------
a    100
b    110
dtype: int64
     性别
张三   男
李四   女
王五   男
陈六   男
----------------------------------
张三    0
李四    1
王五    0
陈六    0
Name: 性别, dtype: int64
----------------------------------
张三    0
李四    1
王五    0
陈六    0
Name: 性别, dtype: int64
    A   B   C   D
a  10  20  30  40
b  11  22  33  44
    A   B   C   D
a  20  30  40  50
b  21  32  43  54